### ISSUE TITLE
Correctness of shannon transfer entropy

### ISSUE THREAD

**Issue by emabe** [cran/RTransferEntropy#1]
Hi,

I am not sure about the implementation of the te_shannon_entropy. In the vignette of the package you claim to compute the KL-divergence between p(i_{t+1} | i_t, j_t) and p(i_{t+1} | i_t) to assess the causal relationship of process J on process I. Then the KL divergence should be
$$
\sum_{i,j} p(i_{t+1} | i_t, j_t) log( p(i_{t+1} | i_t, j_t) / p(i_{t+1} | i_t))
$$

Why are you not dividing k1_j[i] by the factor p2 (as inside the parenthesis) in line 33 of calc_te_shannon.R script? I mean, you want to compute a conditional probability -like on the nominator inside the parenthesis-, not the joint one, right?

Or am I missing something?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. THanks!
